dist: trusty
language: dart
dart:
  - dev
  - stable
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
cache:
  directories:
    - $HOME/.pub-cache

before_install:
  - if [ "$INSTALL_BAZEL" == "true" ]; then wget https://github.com/bazelbuild/bazel/releases/download/0.5.1/bazel_0.5.1-linux-x86_64.deb; sudo dpkg -i bazel_0.5.1-linux-x86_64.deb; fi

# Check for analysis issues, run the test cases, and ensure `dartfmt` is run.
dart_task:
  - test: --platform vm
  - dartanalyzer
  - dartfmt

# The Dart language is constantly being worked on, and sometimes the dev and
# stable builds don't agree on what is considered formatted or what is analysis
# warning free (though this does not effect _using_ the library, likely).
#
# We exclude `dev` from analysis and formatting checks.
matrix:
  allow_failure:
    - dart: dev
      dart_task: dartfmt
    - dart: dev
      dart_task: dartanalyzer
