name: bazel_ipc
description: >
  Communicates with the Bazel Build System.
version: 0.1.0
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/bazel_ipc

environment:
  sdk: ">=1.22.0 <2.0.0"

dependencies:
  collection: ^1.0.0
  meta: ^1.0.5
  protobuf: ^0.5.0

dev_dependencies:
  test: ^0.12.0
